service: api

custom:
  settings:
    USERS_TABLE: users

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.USERS_TABLE}"

functions:
  createuser:
    handler: handler.createuser
    events:
      - http:
          path: /user
          method: post
  getAllusers:
    handler: handler.getAllusers
    events:
      - http:
          path: /users
          method: get
  getusers:
    handler: handler.getusers
    events:
      - http:
          path: /users/{number}
          method: get
  getuser:
    handler: handler.getuser
    events:
      - http:
          path: /user/{id}
          method: get
  updateuser:
    handler: handler.updateuser
    events:
      - http:
          path: /user/{id}
          method: put
  deleteuser:
    handler: handler.deleteuser
    events:
      - http:
          path: /user/{id}
          method: delete

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.USERS_TABLE}
